### ISSUE TITLE
A RemoteServiceException

### ISSUE THREAD

**Issue by quoine-lili-tan** [HeyAlex/WidgetUpdateHelper#5]
Hi Alex,
I got this kind of crash error when I'm using your project.

> Fatal Exception: android.app.RemoteServiceException
> Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{heyalex.widgethelper.WidgetUpdateService}
> android.app.ActivityThread$H.handleMessage (ActivityThread.java:2067)

Do you have any suggestion?
Thanks

**Comment by HeyAlex** [comment]
Hi! seems like **WidgetUpdateService** invoked in wrong way. In last release this behavior should be fixed. Can you check on latest version (v1.4)?
